layout_spectrum: 0.003112126
typography_spectrum: 0.3073564
color:
  saturation: 0.7537048
  lightness: 0.6055722
  brandStrength: 0.7279631
  rhythmicContrast: 0.5230028
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: "PS Pays d'Ozon"
