name: "PS Pays d'Ozon"
favicon: null
layout_spectrum: 0.50385
typography_spectrum: 0.48651
title: "PS Pays d'Ozon"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e00140'
    - '#ffffff'
    - '#070707'
    - '#009d87'
    - '#da6540'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
