name: "PS Pays d'Ozon"
favicon: null
layout_spectrum: 0.003112126
typography_spectrum: 0.3073564
title: "PS Pays d'Ozon"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e20241'
    - '#ffffff'
    - '#c3d007'
    - '#000000'
    - '#6b696d'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
